"""
This script reads documentation from /mpe2 and puts it into md files inside the docs/ directory
"""

import os
import re


def add_frontmatter(text, frontmatter_options):
    frontmatter_text = "---\nautogenerated:"
    for key, value in frontmatter_options.items():
        frontmatter_text += f"\n{key}: {value}"
    frontmatter_text += "\n---\n\n"
    return frontmatter_text + text


def create_docs_md(file_path, text, frontmatter_options):
    text = add_frontmatter(text, frontmatter_options)
    with open(file_path, "w", encoding="utf-8") as file:
        file.write(text)


def get_docs_from_py(file_path):
    print(file_path)
    with open(file_path, encoding="utf-8") as fp:
        text = fp.read()
        regex = re.compile(r'^r?"""\s*((\n|.)*?)("""\s*\n)', re.MULTILINE)
        match = regex.search(text)
        if match:
            return match.group(1)
        else:
            return ""


if __name__ == "__main__":
    ignore_dirs = ["_mpe_utils"]
    docs_dir = os.path.join(os.path.dirname(__file__), "..")
    envs_dir = os.path.join(os.path.dirname(__file__), "..", "..", "mpe2")

    for i,env_name in enumerate(os.listdir(envs_dir)):
        env_path = os.path.join(envs_dir, env_name)
        if not os.path.isdir(env_path) or env_name in ignore_dirs:
            continue
        
        frontmatter_options = {
            "env_icon": f'"../../../_static/img/icons/{env_name}.png"'
        }

        if i == 0:
            frontmatter_options["firstpage"] = ""
        elif i == len(os.listdir(envs_dir)) - 1:
            frontmatter_options["lastpage"] = ""

        docs_text = get_docs_from_py(
            os.path.join(env_path, env_name + ".py")
        )

            
        docs_text += f"""## API
```{{eval-rst}}
.. currentmodule:: mpe2.{env_name}.{env_name}

.. autoclass:: env
.. autoclass:: raw_env
   :members:
```
"""
        docs_env_path = os.path.join(
                docs_dir,
                "environments",
                env_name + ".md",
            )
        create_docs_md(
                docs_env_path,
                docs_text,
                frontmatter_options,
            )
